### ISSUE TITLE
Disable SSL

### ISSUE THREAD

**Issue by seyo-IV** [bastillion-io/Bastillion#294]
I have already tried this, but it doesen't seem to work anymore [51](https://github.com/bastillion-io/Bastillion/issues/51)
My nginx already terminates ssl.

**Comment by seyo-IV** [comment]
iv tried it but the server stops after 5 seconds. The log says the adress is already in use. It trys to bind 8080 even if i changed it to another port.

Thats the Log:
`Caused by: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8080
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:346)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:308)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:394)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1572)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1512)
        ... 9 more
Caused by: java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:461)
        at java.base/sun.nio.ch.Net.bind(Net.java:453)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342)
        ... 17 more
`

**Comment by skavanagh** [comment]
soo you already have something running on port 8080

**Comment by skavanagh** [comment]
either find what's running on 8080 and kill it or you change the http port to something else

https://www.bastillion.io/docs/installation/ports/

**Comment by seyo-IV** [comment]
okay my bad, i had to uncomment `## Connector port to listen on
 jetty.http.port=8088`
