### ISSUE TITLE
not working with supervisor

### ISSUE THREAD

**Issue by palayo** [bastillion-io/Bastillion#310]
I set up Bastillion and it works ! It's quite nice! Thanks a lot.
I wanted Bastillion startup automatically after reboot and keep working as a daemon.
So I used supervisor.
But after supervisor tried start Bastillion, it stopped in a few seconds.
And then, Bastillion does not work again even if I run sh or java command.
How do I keep Bastillion working?
Log is below.

2019-06-26 23:59:00.597:INFO:oejs.Server:main: jetty-9.4.15.v20190215; built: 2019-02-15T16:53:49.381Z; git: eb70b240169fcf1abbd86af36482d1c49826fa0b; jvm 12.0.1-BellSoft+12
2019-06-26 23:59:00.690:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///home/pi/Bastillion-jetty/jetty/webapps/] at interval 1
2019-06-26 23:59:08.480:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=6333ms
2019-06-26 23:59:10.240:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2019-06-26 23:59:10.241:INFO:oejs.session:main: No SessionScavenger set, using defaults
2019-06-26 23:59:10.245:INFO:oejs.session:main: node0 Scavenging every 660000ms
2019-06-26 23:59:24.454:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@19e9475{/,file:///home/pi/Bastillion-jetty/jetty/bastillion/,AVAILABLE}{/home/pi/Bastillion-jetty/jetty/bastillion}
2019-06-26 23:59:24.506:WARN:oejx.XmlConfiguration:main: 
java.security.PrivilegedActionException: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8443
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:555)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1511)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:220)
	at org.eclipse.jetty.start.Main.start(Main.java:490)
	at org.eclipse.jetty.start.Main.main(Main.java:77)
Caused by: 
java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8443
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:346)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:308)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:394)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1572)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1512)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:551)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1511)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:220)
	at org.eclipse.jetty.start.Main.start(Main.java:490)
	at org.eclipse.jetty.start.Main.main(Main.java:77)
Caused by: 
java.net.BindException: アドレスは既に使用中です
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:455)
	at java.base/sun.nio.ch.Net.bind(Net.java:447)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:219)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:308)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:394)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1572)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1512)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:551)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1511)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:220)
	at org.eclipse.jetty.start.Main.start(Main.java:490)
	at org.eclipse.jetty.start.Main.main(Main.java:77)
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:220)
	at org.eclipse.jetty.start.Main.start(Main.java:490)
	at org.eclipse.jetty.start.Main.main(Main.java:77)
Caused by: java.security.PrivilegedActionException: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8443
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:555)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1511)
	... 7 more
Caused by: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8443
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:346)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:308)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:394)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1572)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1512)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:551)
	... 8 more
Caused by: java.net.BindException: アドレスは既に使用中です
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:455)
	at java.base/sun.nio.ch.Net.bind(Net.java:447)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:219)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342)
	... 17 more
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:220)
	at org.eclipse.jetty.start.Main.start(Main.java:490)
	at org.eclipse.jetty.start.Main.main(Main.java:77)
Caused by: java.security.PrivilegedActionException: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8443
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:555)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1511)
	... 7 more
Caused by: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8443
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:346)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:308)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:394)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1572)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1512)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:551)
	... 8 more
Caused by: java.net.BindException: アドレスは既に使用中です
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:455)
	at java.base/sun.nio.ch.Net.bind(Net.java:447)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:219)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342)
	... 17 more

Usage: java -jar $JETTY_HOME/start.jar [options] [properties] [configs]
       java -jar $JETTY_HOME/start.jar --help  # for more information

**Comment by skavanagh** [comment]
I've never used supervisor.  Instructions are here on how to setup Bastillion as a service

https://www.bastillion.io/docs/installation/service/

**Comment by palayo** [comment]
I could set up Bastillion as a service. Thanks!
I have another question.
Bastillion asks the db password at first execution.
Can I specify the db password using command or files? 
I don't like interactive mode for automation.

**Comment by skavanagh** [comment]
you can preset it here

https://github.com/bastillion-io/Bastillion/blob/master/src/main/resources/BastillionConfig.properties#L54

or set it as an environment var

export DBPASSWORD=<whatever>

**Comment by lucapalano** [comment]
Hi @palayo,

I think that configure the supervisord daemon to manage bastillion could be useful for some users. If you have a procedure to manage bastillion via supervisor, could you please share it? (@skavanagh It could be eventually added to the documentation)

Thank you in advance,
Luca

**Comment by palayo** [comment]
sorry to be late for thanks.
I could set up bastillion as a service. It's really usefull.
>lucapalano
I haven't tried to use supervisor after skavanagh's reply. sorry...

**Comment by palayo** [comment]
I could set up bastillion with supervisor and share the way as follow.

1. modify the startBastillion.sh.
Export environment variable DBPASSWORD is required for only first execution.
Specify full path of jetty and java because called by supervisor daemon.
--------------
#!/bin/bash
export DBPASSWORD="dbpasswd"
cd $(cd $(dirname $0);pwd)/jetty;
/usr/lib/jvm/jdk-12.0.1/bin/java -Xms512m -Xmx512m -jar start.jar
--------------
2. make conf file for supervisor.
/etc/supervisor/conf.d/bastillion.conf
---------------
[program:bastillion]
command=/opt/Bastillion-jetty/startBastillion.sh
numprocs=1
user=root
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/bastillion.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=5
stdout_capture_maxbytes=1MB
---------------

Now, I could start/stop bastillion using supervisorctl.
$ supervisorctl start bastillion
$ supervisorctl stop bastillion

I hope this would help someone...
